### ISSUE TITLE
Files should be visible in github, no more .zip files

### ISSUE THREAD

**Issue by 1RedOne** [Skatterbrainz/cmwt#13]
Love the idea behind this project.  Think contributing would be a lot easier if files weren't stored in a zip as they are today.  If files were listed here with a native directory structure, my single file, single line change could be more visible than today, where it would look like a +2KB change in size of the zip.

If you'd like to have separate releases, those could be tracked as separate branches of the project.

Good work dude! 🍰

**Comment by Skatterbrainz** [comment]
Agreed, but need to finish building out missing parts.  Overall it's about 75% "there" right now.  As soon as I'm within 95% I will do that and open it up (the proper way).  Thank you for putting this on the list - it will help make sure I don't forget. :)

**Comment by Skatterbrainz** [comment]
2016.12.07 code files have been uploaded to a new branch.  Still figuring out the sub-folder issue, but may need to use ZIP for image files for now at least.

**Comment by Skatterbrainz** [comment]
Latest build is under new branch and will be merged when milestones are reached.
